(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(apropos-do-all t)
 '(auto-save-default nil)
 '(create-lockfiles nil)
 '(cursor-in-non-selected-windows nil)
 '(custom-file (expand-file-name "custom.el" user-emacs-directory))
 '(delete-by-moving-to-trash t)
 '(desktop-load-locked-desktop nil)
 '(enable-recursive-minibuffers t)
 '(ffap-machine-p-known 'reject)
 '(ffap-machine-p-unknown 'reject)
 '(fill-column 80)
 '(fit-frame-to-buffer-margins '(100 100 100 100))
 '(fit-window-to-buffer-horizontally t)
 '(fringe-mode 6 nil (fringe))
 '(help-window-select t)
 '(initial-scratch-message nil)
 '(isearch-allow-scroll 'unlimited)
 '(lazy-highlight-initial-delay 0)
 '(load-prefer-newer t)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(ns-command-modifier 'meta)
 '(ns-option-modifier 'super)
 '(ns-pop-up-frames 'fresh)
 '(ns-use-native-fullscreen nil)
 '(ns-use-thin-smoothing t)
 '(package-archive-priorities
   '(("melpa" . 10)
     ("melpa-stable" . 5)
     ("gnu" . 0)
     ("marmalade" . -5)))
 '(package-archives
   '(("melpa" . "https://melpa.org/packages/")
     ("melpa-stable" . "https://stable.melpa.org/packages/")
     ("org" . "http://orgmode.org/elpa/")
     ("gnu" . "http://elpa.gnu.org/packages/")))
 '(package-menu-hide-low-priority t)
 '(package-quickstart t)
 '(package-quickstart-file "/home/cmccloud/.emacs.d/var/package-quickstart.el")
 '(package-selected-packages
   '(magit yasnippet which-key use-package treemacs-all-the-icons posframe no-littering lsp-mode lispy helm-xref helm-themes helm-descbinds frame-local elisp-slime-nav doom-themes doom-modeline company))
 '(package-user-dir "/home/cmccloud/.emacs.d/elpa")
 '(save-interprogram-paste-before-kill t)
 '(scroll-bar-mode t)
 '(search-whitespace-regexp ".*")
 '(show-paren-delay 0)
 '(split-height-threshold nil)
 '(tool-bar-mode nil)
 '(use-package-always-defer t)
 '(use-package-expand-minimally nil)
 '(use-package-minimum-reported-time 0.01)
 '(user-full-name "Christopher McCloud")
 '(user-mail-address "mccloud.christopher@gmail.com")
 '(visible-cursor nil)
 '(window-combination-resize t)
 '(window-divider-default-bottom-width 2)
 '(window-divider-default-right-width 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 100 :family "Input"))))
 '(helm-candidate-number ((t (:inherit bold :background nil))))
 '(helm-match ((t (:inherit font-lock-keyword-face :weight bold)))))
